version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "CloveTwilightBOT"
    assignees:
      - "CloveTwilightBOT"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
