name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"  # Run twice a day to avoid hitting rate limits
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set write permissions
    
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
