name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Or your default branch
    paths-ignore:
      - '**.md'  # Prevents infinite loop by ignoring changes to markdown files

jobs:
  update-readme:
    name: Update README with Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
